name: empathos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1         # Check for the latest version
  face_camera: ^0.1.4       # Or the latest version available
  package_info_plus: ^8.3.0
  http: ^1.3.0
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
